name: Lab final DevOps

on: push 

jobs: 
  build:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3

      - name: Configuração do Docker
        uses: docker/setup-compose-action@v1

      - name: Build Imagem Docker
        run: docker compose up

  testes: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configuração do Docker
        uses: docker/setup-compose-action@v1
      
      - name: Comando de testes
        run: docker compose run api python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Etapa de Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-d0vnjp2li9vc73d2qb30?key=J1uOnp9oAv8"